version: "3.7"

services: 
  db_test:
    image: postgres:14.0-alpine
    container_name: db_test
    environment:
      POSTGRES_DB: queue_system
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  backend_test:
    image: golang:1.17.1-alpine
    container_name: backend_test
    working_dir: /__w/queue-system/queue-system/backend
    stdin_open: true
    tty: true
    environment:
      SECRET_PATH: /__w/queue-system/queue-system/envs/secret_test
      ENV_PATH: /__w/queue-system/queue-system/envs/env_test
    volumes:
      - ../:/__w/queue-system/queue-system