// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jerry0420/queue-system/backend/domain"
	mock "github.com/stretchr/testify/mock"

	pgDB "github.com/jerry0420/queue-system/backend/repository/pgDB"
)

// PgDBQueueRepositoryInterface is an autogenerated mock type for the PgDBQueueRepositoryInterface type
type PgDBQueueRepositoryInterface struct {
	mock.Mock
}

// CreateQueues provides a mock function with given fields: ctx, tx, storeID, queues
func (_m *PgDBQueueRepositoryInterface) CreateQueues(ctx context.Context, tx pgDB.PgDBInterface, storeID int, queues []domain.Queue) error {
	ret := _m.Called(ctx, tx, storeID, queues)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgDB.PgDBInterface, int, []domain.Queue) error); ok {
		r0 = rf(ctx, tx, storeID, queues)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
